import type { PramericaTestData } from "../types";

export function buildSteps(d: PramericaTestData) {
  const otp = `${d.otp1}${d.otp2}${d.otp3}${d.otp4}${d.otp5}${d.otp6}`;
  const otpSteps = otp.split("").map((v, i) => { console.log(`OTP digit ${i + 1}:`, v); return { action: "fill", selector: `#agentotp${i + 1}`, value: v }; });
  return [
    { action: "goto", value: "https://nvestuat.pramericalife.in/Life/Login.html" },
    { action: "fill", selector: "role=textbox[name='Enter Code']", value: d.agentCode },
    ...otpSteps,
    { action: "click", selector: "role=button[name='Sign In']" },
    { action: "click", selector: "role=button[name='Yes, Force Login']" },
    { action: "click", selector: "role=heading[name='Start New Application']" },
    { action: "fill", selector: "role=textbox[name='Enter Proposer PAN']", value: d.proposerPAN },
    { action: "fill", selector: "role=textbox[name='Enter your mobile number']", value: d.mobileNumber },
    { action: "check", selector: "#kycckecked" },
    { action: "click", selector: "role=button[name='Submit']" },
    { action: "click", selector: "text=Proceed without e-KYC" },
    { action: "select", selector: "#kyc_Title", value: d.title },
    { action: "wait", value: "2000" },
    { action: "fill", selector: "role=textbox[name='Enter First Name']", value: d.firstName },
    { action: "fill", selector: "role=textbox[name='Enter Middle Name']", value: d.middleName },
    { action: "fill", selector: "role=textbox[name='Enter Last Name']", value: d.lastName },
    { action: "select", selector: "#kyc_Gender", value: d.gender },
    { action: "fill", selector: "role=textbox[name='DD/MM/YYYY']", value: d.dateOfBirth },
    { action: "fill", selector: "role=textbox[name='Enter E-mail ID']", value: d.email },
    { action: "fill", selector: "#kyc_TempAddress1", value: d.address1 },
    { action: "fill", selector: "#kyc_TempAddress2", value: d.address2 },
    { action: "fill", selector: "#kyc_TempAddress3", value: d.address3 },
    { action: "fill", selector: "#kyc_LandMark", value: d.landmark },
    { action: "fill", selector: "#kyc_PinCode", value: d.pinCode },
    { action: "click", selector: "#select2-kyc_State-container" },
    { action: "fill", selector: "role=searchbox[name='Search']", value: d.state },
    { action: "press", selector: "role=searchbox[name='Search']", value: "Enter" },
    { action: "click", selector: "#select2-kyc_City-container" },
    { action: "click", selector: `role=option[name='${d.city}']` },
    { action: "check", selector: "#sameAsTempAddress" },
    // { action: "check", selector: "role=checkbox[name='I authorize Pramerica Life']" },
    { action: "check", selector: "#checkboxkyc2" },
    { action: "click", selector: "button.border-0.button-filled.ml-2.h-100 >> nth=1" },
    // { action: "click", selector: "text=Copy" },
    { action: "wait", value: "10000" },
    { action: "click", selector: "role=button[name='Thank you and Proceed']" },
    { action: "fill", selector: "role=textbox[name='Enter total monthly income']", value: d.monthlyIncome },
    { action: "fill", selector: "role=textbox[name='Enter total monthly expenses']", value: d.monthlyExpenses },
    { action: "click", selector: `role=img[name='${d.maritalStatus}']` },
    { action: "click", selector: "#lb_lifeGoal_2" },
    { action: "click", selector: "#lb_risk_2" },
    { action: "click", selector: "#lb_time_2" },
    { action: "click", selector: "role=button[name='Next']" },
    { action: "click", selector: "role=button[name='Buy Now'] >> nth=0" },
    { action: "click", selector: "role=button[name='Next']" },
    { action: "select", selector: "#dynInput_Mode", value: d.premiumMode },
    { action: "select", selector: "#dynPR_CHANNEL", value: d.premiumChannel },
    { action: "select", selector: "#divoption0 >> role=combobox", value: d.premiumFrequency },
    { action: "fill", selector: "role=textbox[name='Premium Amount']", value: d.premiumAmount },
    { action: "click", selector: "role=button[name='Calculate']" },
  ];
}
